version: '3.8'

services:
  app:
    command: python manage.py runserver 0.0.0.0:9001
    image: streamer
    build:
      context: .
    # command: [nginx, '-g', 'daemon off;']
    # privileged: true
    volumes:
      - .:/code
    environment:
      - POSTGRES_HOST=streamerdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - DEBUG=True
    ports:
      - "9001:9001"    
      # - "5004:5004"
      - "6600:6600"
      - "8000:8000"
      # - "1234:1234"

volumes:
  streamerdbdata:
  # web:
  #   image: nginx:1.23.0
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./html:/usr/share/nginx/html:ro
  #   command: [nginx-debug, '-g', 'daemon off;']
  #   ports:
  #     - "8080:8080"

# volumes:
#   shareddata:
#     external: true