version: '3.8'

services:

  icecast:
    command: tail -f /dev/null
    image: icecast
    build:
      context: icecast
    ports:
      - "9000:9000"

  mpc:
    command: tail -f /dev/null
    image: mpc
    build:
      context: mpc
    environment:
      - MPD_HOST_DEFAULT=mpd_default
      - MPD_HOST_DANCEHALL=mpd_dancehall
    depends_on:
      - mpd_dancehall
      - mpd_default

# ====== below is for all the individual players

  mpd_dancehall:
    command: mpd --no-daemon --verbose
    image: mpd
    build:
      context: mpd
    volumes:
      - ./mpd/data:/code/data
    environment:
      - GENRE=dancehall
      - ICECAST_HOST=icecast
    depends_on:
      - icecast

  mpd_default:
    command: mpd --no-daemon --verbose
    image: mpd
    build:
      context: mpd
    volumes:
      - ./mpd/data:/code/data
    environment:
      - GENRE=default
      - ICECAST_HOST=icecast
    depends_on:
      - icecast

