version: '3.8'

services:
  app:
    command: tail -f /var/log/mpd/mpd.log
    image: streamer
    build:
      context: .
    # command: [nginx, '-g', 'daemon off;']
    # privileged: true
    volumes:
      - .:/code
    environment:
      - DIR=folder2
    ports:
      - "8000:8000"

volumes:
  streamerdbdata:
  # web:
  #   image: nginx:1.23.0
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./html:/usr/share/nginx/html:ro
  #   command: [nginx-debug, '-g', 'daemon off;']
  #   ports:
  #     - "8080:8080"

# volumes:
#   shareddata:
#     external: true