version: '3.8'

services:
  app:
    command: tail -f /var/log/mpd/mpd.log
    image: streamer
    build:
      context: .
    # privileged: true
    volumes:
      - .:/code
    environment:
      - DIR=folder1
    ports:
      - "8000:8000"
