version: '3.8'

services:

# ====== these are the players for the different genres

  mpd_default:
    command: mpd --no-daemon --verbose
    image: mpd
    build:
      context: mpd
    volumes:
      - ./data:/code/data
    environment:
      - DIR=default
      - PORT=9000
    ports:
      - "9000:9000"

# ====== below is for controlling the players

  mpc:
    image: mpc
    build:
      context: mpc
    restart: always
    volumes:
      - ./data:/code/data
    environment:
      - DIR=default
      - MPD_HOST=mpd_default
      - MPD_PORT=6600
    depends_on:
      - mpd_default
