version: '3.8'

services:
  mpd_dancehall:
    command: tail -f /var/log/mpd/mpd.log
    image: mpd
    build:
      context: mpd
    volumes:
      - ./mpd/data:/code/data
    environment:
      - GENRE=dancehall
      - ICECAST_HOST=icecast
    depends_on:
      - icecast

  mpd_default:
    command: tail -f /var/log/mpd/mpd.log
    image: mpd
    build:
      context: mpd
    volumes:
      - ./mpd/data:/code/data
    environment:
      - GENRE=default
      - ICECAST_HOST=icecast
    depends_on:
      - icecast

  icecast:
    command: tail -f /dev/null
    image: icecast
    build:
      context: icecast
    # privileged: true
    volumes:
      - ./icecast:/code
    ports:
      - "9000:9000"