version: '3.8'

services:
  # db:
  #   image: postgres:alpine
  #   restart: always
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   env_file:
  #     - db.env

  app:
    image: streamer
    build:
      context: .
    # command: python manage.py runserver 0.0.0.0:9002
    # command: [nginx, '-g', 'daemon off;']
    volumes:
      - .:/code
    environment:
      - POSTGRES_HOST=db
      - DEBUG=True
    env_file:
      - db.env
    depends_on:
      - db
    ports:
      # - "9000:9000"    
      # - "9001:9001"
      # - "9002:9002"
      - "8000:8000"
      - "1234:1234"

  # web:
  #   image: nginx:1.23.0
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./html:/usr/share/nginx/html:ro
  #   command: [nginx-debug, '-g', 'daemon off;']
  #   ports:
  #     - "8080:8080"

volumes:
  db: