apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-default
  namespace: plstreamer
spec:
  selector:
    matchLabels:
      app: player-default
  template:
    metadata:
      labels:
        app: player-default
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: plstreamerdata
      containers:
        - name: player-default
          image: localhost:32000/mpd
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: GENRE
            value: "default"
          - name: PORT
            value: "9000"
          volumeMounts:
          - mountPath: /code
            name: data
        - name: mpc-default
          image: localhost:32000/mpc
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: MPD_HOST
            value: "localhost"
          - name: MPD_PORT
            value: "6600"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-dancehall
  namespace: plstreamer
spec:
  selector:
    matchLabels:
      app: player-dancehall
  template:
    metadata:
      labels:
        app: player-dancehall
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: plstreamerdata
      containers:
        - name: player-dancehall
          image: localhost:32000/mpd
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: GENRE
            value: "dancehall"
          - name: PORT
            value: "9000"
          volumeMounts:
          - mountPath: /code
            name: data
        - name: mpc-dancehall
          image: localhost:32000/mpc
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: MPD_HOST
            value: "localhost"
          - name: MPD_PORT
            value: "6600"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-rnb
  namespace: plstreamer
spec:
  selector:
    matchLabels:
      app: player-rnb
  template:
    metadata:
      labels:
        app: player-rnb
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: plstreamerdata
      containers:
        - name: player-rnb
          image: localhost:32000/mpd
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: GENRE
            value: "rnb"
          - name: PORT
            value: "9000"
          volumeMounts:
          - mountPath: /code
            name: data
        - name: mpc-rnb
          image: localhost:32000/mpc
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: MPD_HOST
            value: "localhost"
          - name: MPD_PORT
            value: "6600"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-80s
  namespace: plstreamer
spec:
  selector:
    matchLabels:
      app: player-80s
  template:
    metadata:
      labels:
        app: player-80s
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: plstreamerdata
      containers:
        - name: player-80s
          image: localhost:32000/mpd
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: GENRE
            value: "80s"
          - name: PORT
            value: "9000"
          volumeMounts:
          - mountPath: /code
            name: data
        - name: mpc-80s
          image: localhost:32000/mpc
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
          env:
          - name: MPD_HOST
            value: "localhost"
          - name: MPD_PORT
            value: "6600"