apiVersion: v1
kind: Service
metadata:
  name: svc-default
  namespace: plstreamer
spec:
  selector:
    app: player-default
  ports:
  - name: app
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: svc-dancehall
  namespace: plstreamer
spec:
  selector:
    app: player-dancehall
  ports:
  - name: app
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: svc-rnb
  namespace: plstreamer
spec:
  selector:
    app: player-rnb
  ports:
  - name: app
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: svc-80s
  namespace: plstreamer
spec:
  selector:
    app: player-80s
  ports:
  - name: app
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort