apiVersion: v1
kind: Service
metadata:
  name: plstreamer-svc
  namespace: plstreamer
spec:
  selector:
    app: app
  ports:
  - name: app
    protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort