apiVersion: v1
kind: Service
metadata:
  name: default-svc
  namespace: plstreamer
spec:
  selector:
    app: player-default
  ports:
  - name: app
    protocol: TCP
    port: 6600
    targetPort: 6600

---

apiVersion: v1
kind: Service
metadata:
  name: dancehall-svc
  namespace: plstreamer
spec:
  selector:
    app: player-dancehall
  ports:
  - name: app
    protocol: TCP
    port: 6600
    targetPort: 6600

---

apiVersion: v1
kind: Service
metadata:
  name: rnb-svc
  namespace: plstreamer
spec:
  selector:
    app: player-rnb
  ports:
  - name: app
    protocol: TCP
    port: 6600
    targetPort: 6600